[[news]]
date = "2026-03"
content = "Presented recent work on collider phenomenology at an institute seminar."

[[news]]
date = "2025-12"
content = "A new paper was uploaded to arXiv and submitted for journal review."

[[news]]
date = "2025-09"
content = "Started a PhD position in high energy physics."
