[[news]]
date = "2024-10"
content = "在“纪念李政道先生会议”（上海，邀请报告）中报告了基于 J/psi 衰变纠缠超子体系的 CP 破坏搜索新方法。"

[[news]]
date = "2024-07"
content = "在 Chin. Phys. C 48 (2024) 073003 发表“Prospects to study hyperon-nucleon interactions at BESIII”。"

[[news]]
date = "2024-01"
content = "开始担任 LHCb Charm 工作组 MC liaison。"
